apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'todo-backend'
      metrics_path: '/metrics'
      static_configs:
      - targets: ['backend:3001']
      relabel_configs:
      - source_labels: [__address__]
        target_label: job
        replacement: 'todo-backend'

    - job_name: 'kube-state-metrics'
      static_configs:
      - targets: ['kube-state-metrics:8080']

    - job_name: 'kubernetes-nodes'
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - replacement: node-exporter
        target_label: job
