apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/
        - name: time-sync
          mountPath: /etc/localtime
          readOnly: true  # Optional: set readOnly to prevent changes
      volumes:
      - name: config
        configMap:
          name: prometheus-config
      - name: time-sync
        hostPath:
          path: /etc/localtime
          type: File
