apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort  # Change to NodePort
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001  
  selector:
    app: backend
